# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main
- releases/*
- feature/*

pool:
  name: pool-test-001

container: node:latest

steps:
- script: npm ci
  displayName: 'Installing dependencies'

- script: npm run test:ci
  displayName: 'Running tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/junit.xml'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    pwd
    node --version
  displayName: 'Run a multi-line script'
