# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main
- releases/*
- feature/*

pool:
  name: pool-test-001

stages: 
- stage: Build
  jobs:
  - job:
    container: node:latest
    steps:
    - script: npm ci
      displayName: 'Installing dependencies'
- stage: Testing
  jobs:
  - job:
    container: node:latest
    steps:
    - script: npm run test:ci
      displayName: 'Running tests'
  - job:
    container: mcr.microsoft.com/azure-functions/dotnet:3.0-slim
    steps:
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunner: JUnit
        testResultsFiles: '**/junit.xml'
    - task: PublishCodeCoverageResults@1
      inputs: 
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/reports/coverage/*coverage.xml'
        # reportDirectory: '$(System.DefaultWorkingDirectory)/reports/coverage'
